spring:
  profiles:
    active: dev

server:
  port: 8080

mybatis:
  config-location: classpath:/sql/configuration.xml
  mapper-locations: classpath:/sql/xml/sql-*.xml

---

spring:
  config:
    activate:
      on-profile: dev
  datasource:
    hikari:
      pool-name: hikari
      maximum-pool-size: 10
      max-lifetime: 1800000
      connection-timeout: 30000
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: "jdbc:log4jdbc:h2:mem:musinsa;MODE=MySQL"
    username: sa
    password:
  sql:
    init:
      schema-locations: classpath:h2-schema.sql
      data-locations: classpath:h2-data.sql

---

spring:
  config:
    activate:
      on-profile: test
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    hikari:
      pool-name: hikari
      maximum-pool-size: 10
      max-lifetime: 1800000
      connection-timeout: 30000
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: "jdbc:log4jdbc:h2:mem:musinsa_testdb;MODE=MySQL"
    username: sa
    password:
  sql:
    init:
      schema-locations: classpath:h2-schema.sql
      data-locations: classpath:h2-data.sql


